name: Test

on:
  push:
    paths-ignore:
      - "**.md"
      - "data/**"
      - "docs/**"

  pull_request:
    branches: ["develop"]
    paths-ignore:
      - "**.md"
      - "data/**"
      - "docs/**"

jobs:
  test-code:
    name: Test code
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Set up Poetry
        run: |
          python -m pip install poetry
          python -m poetry config --local -- virtualenvs.create true
          python -m poetry config --local -- virtualenvs.in-project true

      - name: Cache Python virtual environment
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: |
          python -m poetry install

      - name: Run tests
        run: |
          poetry run python -m unittest discover

  test-migrations:
    name: Test migrations
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Set up Poetry
        run: |
          python -m pip install poetry
          python -m poetry config --local -- virtualenvs.create true
          python -m poetry config --local -- virtualenvs.in-project true

      - name: Cache Python virtual environment
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-venv-migrations-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: |
          python -m poetry install

      - name: Run migration tests
        run: |
          poetry run python -m unittest discover tests.integration.migrations -v

  lint-format-code:
    name: Lint and format code
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ruff

      - name: Lint code
        run: |
          ruff check --output-format=github .

      - name: Format code
        run: |
          ruff format --check .
